#!/bin/bash

cd ~/thesis/SWE
rm build/build_SWE_gnu_release_none_fwave/ build/SWE_gnu_release_none_fwave_1 build/SWE_gnu_release_none_fwave_2  build/output/* -rf
scons buildVariablesFile=build/options/SWE_gnu.py
