#!/bin/bash

cd ~/thesis/SWE/build
rm output/*

if  [ $1 = 1 ];then
  ./SWE_gnu_release_none_fwave_1 -x 320 -y 320 -o output/testrun1
elif [ $1 = "2" ]; then
  ./SWE_gnu_release_none_fwave_2 -x 320 -y 320 -o output/testrun2
elif [ $1 == "b" ]; then
  ./SWE_gnu_release_none_fwave_2 -x 320 -y 320 -o output/testrun1
  ./SWE_gnu_release_none_fwave_2 -x 320 -y 320 -o output/testrun2
else
  echo "not valid option"
fi
