#!/bin/bash

cd ~/thesis/SWE/build
rm  precice-Solver* reference.xml output/*

size=40

if  [ $1 == "1" ];then
  ./SWE_gnu_debug_none_fwave_1 -x $size -y $size -o output/testrun1
elif [ $1 == "2" ]; then
  ./SWE_gnu_debug_none_fwave_2 -x $size -y $size -o output/testrun2
elif [ $1 == "b" ]; then
   ./SWE_gnu_debug_none_fwave_1 -x $size -y $size -o output/testrun1
   ./SWE_gnu_debug_none_fwave_2 -x $size -y $size -o output/testrun2
else
  echo "not valid option"
fi
 cd ..
