#!/bin/bash

sed -i 's/height/heightS1/g' build/precice-config.xml
sed -i 's/\bhu\b/huS1/g' build/precice-config.xml
sed -i 's/\bhv\b/hvS1/g' build/precice-config.xml

sed -i 's/\bheightId\b/heightS1Id/g' src/examples/swe_simple_*.cpp
sed -i 's/\bhuId\b/huS1Id/g' src/examples/swe_simple_*.cpp
sed -i 's/\bhvId\b/hvS1Id/g' src/examples/swe_simple_*.cpp

sed -i 's/\bheight\b/heightS1/g' src/examples/swe_simple_*.cpp
sed -i 's/\bhu\b/huS1/g' src/examples/swe_simple_*.cpp
sed -i 's/\bhv\b/hvS1/g' src/examples/swe_simple_*.cpp

sed -i 's/\bheight_db\b/heightS1_db/g' src/examples/swe_simple_*.cpp
sed -i 's/\bhu_db\b/huS1_db/g' src/examples/swe_simple_*.cpp
sed -i 's/\bhv_db\b/hvS1_db/g' src/examples/swe_simple_*.cpp
